version: "3.8"

networks:
  my-bridge:
    driver: bridge

services:
  redis-server:
    image: redis:latest
    networks:
      - my-bridge

  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis-server
    networks:
      - my-bridge
